//https://learn.microsoft.com/en-us/sql/t-sql/functions/configuration-functions-transact-sql?view=sql-server-ver16
module.exports = {
  configuration_functions: $ => $._config_global_var,

  _config_global_var: $ => token(prec(1, choice(
    '@@CONNECTIONS',
    '@@CPU_BUSY',
    '@@DATEFIRST',
    '@@DBTS',
    '@@ERROR',
    '@@IDENTITY',
    '@@IDLE',
    '@@IO_BUSY',
    '@@LANGID',
    '@@LANGUAGE',
    '@@LOCK_TIMEOUT',
    '@@MAX_CONNECTIONS',
    '@@MAX_PRECISION',
    '@@NESTLEVEL',
    '@@OPTIONS',
    '@@PACKET_ERRORS',
    '@@PACK_RECEIVED',
    '@@PACK_SENT',
    '@@PROCID',
    '@@REMSERVER',
    '@@ROWCOUNT',
    '@@SERVERNAME',
    '@@SERVICENAME',
    '@@SPID',
    '@@TEXTSIZE',
    '@@TIMETICKS',
    '@@TOTAL_ERRORS',
    '@@TOTAL_READ',
    '@@TOTAL_WRITE',
    '@@TRANCOUNT',
    '@@VERSION',
  ))),
};
