/**
 * External scanner for tree-sitter-tsql.
 *
 * Provides a _non_keyword_id token that matches the identifier pattern
 * [A-Za-z_#][A-Za-z_#$@0-9]* but REJECTS all T-SQL grammar keywords.
 *
 * This prevents the word: property from demoting keywords (like FROM,
 * SELECT, WHERE, AVG, COUNT) into identifiers. Non-reserved keywords
 * that are allowed as identifiers (like STATUS, TYPE, NAME) are handled
 * separately by the _keyword rule in grammar.js.
 *
 * Uses binary search on a sorted keyword table for O(log n) lookup.
 */

#include "tree_sitter/parser.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

enum TokenType {
  NON_KEYWORD_ID,
};

/* --- Sorted keyword table (uppercase, C-locale / ASCII byte order) --- */
/* All keyword tokens from grammar.js and grammar/functions/*.js          */
/* MUST be sorted by ASCII byte value (LC_ALL=C sort) for binary search  */

static const char *KEYWORDS[] = {
  "ABS",
  "ABSENT",
  "ABSOLUTE",
  "ACOS",
  "ADD",
  "AFTER",
  "ALL",
  "ALTER",
  "AND",
  "ANSI_DEFAULTS",
  "ANSI_NULLS",
  "ANSI_NULL_DFLT_OFF",
  "ANSI_NULL_DFLT_ON",
  "ANSI_PADDING",
  "ANSI_WARNINGS",
  "ANY",
  "APPLOCK_MODE",
  "APPLOCK_TEST",
  "APPLY",
  "APPROX_COUNT_DISTINCT",
  "APPROX_PERCENTILE_CONT",
  "APPROX_PERCENTILE_DISC",
  "APP_NAME",
  "ARITHABORT",
  "ARITHIGNORE",
  "AS",
  "ASC",
  "ASCII",
  "ASIN",
  "ASSEMBLYPROPERTY",
  "ASYMKEYPROPERTY",
  "ASYMKEY_ID",
  "ASYMMETRIC",
  "AT",
  "ATAN",
  "ATN2",
  "AUTHORIZATION",
  "AUTO",
  "AVG",
  "BACKUP",
  "BEGIN",
  "BETWEEN",
  "BIGINT",
  "BINARY",
  "BINARY_BASE64",
  "BINARY_CHECKSUM",
  "BIT",
  "BIT_COUNT",
  "BIT_LENGTH",
  "BREAK",
  "BROWSE",
  "BULK",
  "BY",
  "CACHE",
  "CALLER",
  "CASCADE",
  "CASE",
  "CAST",
  "CATCH",
  "CEILING",
  "CERTENCODED",
  "CERTIFICATE",
  "CERTPRIVATEKEY",
  "CERTPROPERTY",
  "CERT_ID",
  "CHANGES",
  "CHANGETABLE",
  "CHAR",
  "CHARINDEX",
  "CHECK",
  "CHECKPOINT",
  "CHECKSUM",
  "CHECKSUM_AGG",
  "CHOOSE",
  "CLOSE",
  "CLUSTERED",
  "COALESCE",
  "COLLATE",
  "COLLATIONPROPERTY",
  "COLUMN",
  "COLUMNPROPERTY",
  "COL_LENGTH",
  "COL_NAME",
  "COMMIT",
  "COMMITTED",
  "COMPRESS",
  "CONCAT",
  "CONCAT_NULL_YIELDS_NULL",
  "CONCAT_WS",
  "CONNECTIONPROPERTY",
  "CONSTRAINT",
  "CONTAINED",
  "CONTAINS",
  "CONTAINSTABLE",
  "CONTEXT_INFO",
  "CONTINUE",
  "CONVERT",
  "COOKIE",
  "COS",
  "COT",
  "COUNT",
  "COUNT_BIG",
  "CREATE",
  "CROSS",
  "CRYPT_GEN_RANDOM",
  "CUBE",
  "CUME_DIST",
  "CURRENT",
  "CURRENT_DATE",
  "CURRENT_REQUEST_ID",
  "CURRENT_TIME",
  "CURRENT_TIMESTAMP",
  "CURRENT_TIMEZONE",
  "CURRENT_TIMEZONE_ID",
  "CURRENT_TRANSACTION_ID",
  "CURRENT_USER",
  "CURSOR",
  "CURSOR_CLOSE_ON_COMMIT",
  "CURSOR_STATUS",
  "CYCLE",
  "D",
  "DATABASE",
  "DATABASEPROPERTYEX",
  "DATABASE_PRINCIPAL_ID",
  "DATALENGTH",
  "DATE",
  "DATEADD",
  "DATEDIFF",
  "DATEDIFF_BIG",
  "DATEFROMPARTS",
  "DATENAME",
  "DATEPART",
  "DATETIME",
  "DATETIME2",
  "DATETIME2FROMPARTS",
  "DATETIMEFROMPARTS",
  "DATETIMEOFFSET",
  "DATETIMEOFFSETFROMPARTS",
  "DATETRUNC",
  "DATE_BUCKET",
  "DBCC",
  "DB_ID",
  "DB_NAME",
  "DEALLOCATE",
  "DECIMAL",
  "DECLARE",
  "DECOMPRESS",
  "DECRYPTBYASYMKEY",
  "DECRYPTBYCERT",
  "DECRYPTBYKEY",
  "DECRYPTBYPASSPHRASE",
  "DECRYPTION",
  "DEFAULT",
  "DEGREES",
  "DELAY",
  "DELETE",
  "DELETED",
  "DENSE_RANK",
  "DENY",
  "DESC",
  "DIFFERENCE",
  "DISABLE",
  "DISK",
  "DISTINCT",
  "DISTRIBUTED",
  "DOUBLE",
  "DROP",
  "DYNAMIC",
  "E",
  "ELEMENTS",
  "ELSE",
  "ENABLE",
  "ENCRYPTBYASYMKEY",
  "ENCRYPTBYCERT",
  "ENCRYPTBYKEY",
  "ENCRYPTBYPASSPHRASE",
  "ENCRYPTION",
  "END",
  "EOMONTH",
  "ERROR_LINE",
  "ERROR_MESSAGE",
  "ERROR_NUMBER",
  "ERROR_PROCEDURE",
  "ERROR_SEVERITY",
  "ERROR_STATE",
  "ESCAPE",
  "EXCEPT",
  "EXEC",
  "EXECUTE",
  "EXIST",
  "EXISTS",
  "EXP",
  "EXPAND_VIEWS",
  "EXPLICIT",
  "FAST",
  "FAST_FORWARD",
  "FETCH",
  "FILE",
  "FILEGROUP",
  "FILEGROUPPROPERTY",
  "FILEGROUP_ID",
  "FILEGROUP_NAME",
  "FILEGROWTH",
  "FILENAME",
  "FILEPROPERTY",
  "FILEPROPERTYEX",
  "FILE_ID",
  "FILE_IDEX",
  "FILE_NAME",
  "FIRST",
  "FIRST_VALUE",
  "FLOAT",
  "FLOOR",
  "FMTONLY",
  "FOLLOWING",
  "FOR",
  "FORCE",
  "FORCEPLAN",
  "FOREIGN",
  "FORMAT",
  "FORMATMESSAGE",
  "FORWARD_ONLY",
  "FREETEXT",
  "FREETEXTTABLE",
  "FROM",
  "FULL",
  "FULLTEXTCATALOGPROPERTY",
  "FULLTEXTSERVICEPROPERTY",
  "FUNCTION",
  "GEOGRAPHY",
  "GEOMETRY",
  "GET",
  "GETANCESTOR",
  "GETANSINULL",
  "GETDATE",
  "GETDESCENDANT",
  "GETLEVEL",
  "GETREPARENTEDVALUE",
  "GETROOT",
  "GETUTCDATE",
  "GET_BIT",
  "GET_FILESTREAM_TRANSACTION_CONTEXT",
  "GLOBAL",
  "GO",
  "GOTO",
  "GRANT",
  "GREATEST",
  "GROUP",
  "GROUPING",
  "GROUPING_ID",
  "HASH",
  "HASHBYTES",
  "HAS_DBACCESS",
  "HAS_PERMS_BY_NAME",
  "HAVING",
  "HIDDEN",
  "HIERARCHYID",
  "HISTORY_TABLE",
  "HOLDLOCK",
  "HOST_ID",
  "HOST_NAME",
  "IDENTITY",
  "IDENTITY_INSERT",
  "IDENT_CURRENT",
  "IDENT_INCR",
  "IDENT_SEED",
  "IF",
  "IIF",
  "IMAGE",
  "IMMEDIATE",
  "IMPLICIT_TRANSACTIONS",
  "IN",
  "INCLUDE",
  "INCLUDE_NULL_VALUES",
  "INCREMENT",
  "INDEX",
  "INDEXKEY_PROPERTY",
  "INDEXPROPERTY",
  "INDEX_COL",
  "INNER",
  "INSERT",
  "INSERTED",
  "INSTEAD",
  "INT",
  "INTERSECT",
  "INTO",
  "IS",
  "ISDATE",
  "ISDESCENDANTOF",
  "ISJSON",
  "ISNULL",
  "ISNUMERIC",
  "ISOLATION",
  "IS_MEMBER",
  "IS_OBJECTSIGNED",
  "IS_ROLEMEMBER",
  "IS_SRVROLEMEMBER",
  "JOB",
  "JOIN",
  "JSON",
  "JSON_ARRAY",
  "JSON_MODIFY",
  "JSON_OBJECT",
  "JSON_PATH_EXISTS",
  "JSON_QUERY",
  "JSON_VALUE",
  "KEEP",
  "KEY",
  "KEYS",
  "KEYSET",
  "KEY_GUID",
  "KEY_ID",
  "KEY_NAME",
  "KILL",
  "LAG",
  "LANGUAGE",
  "LAST",
  "LAST_VALUE",
  "LEAD",
  "LEAST",
  "LEFT",
  "LEFT_SHIFT",
  "LEN",
  "LEVEL",
  "LIKE",
  "LINENO",
  "LOCAL",
  "LOCK_ESCALATION",
  "LOG",
  "LOG10",
  "LOGIN",
  "LOGINPROPERTY",
  "LOOP",
  "LOWER",
  "LTRIM",
  "M",
  "MASTER",
  "MATCHED",
  "MAX",
  "MAXDOP",
  "MAXRECURSION",
  "MAXSIZE",
  "MAXVALUE",
  "MEMBER",
  "MERGE",
  "MIN",
  "MINVALUE",
  "MIN_ACTIVE_ROWVERSION",
  "MIRROR",
  "MODIFY",
  "MONEY",
  "MOVE",
  "N",
  "NAME",
  "NCHAR",
  "NEWID",
  "NEWSEQUENTIALID",
  "NEXT",
  "NO",
  "NOCHECK",
  "NOCOUNT",
  "NODES",
  "NOEXEC",
  "NOLOCK",
  "NONCLUSTERED",
  "NONE",
  "NOT",
  "NOTIFICATION",
  "NOWAIT",
  "NO_WAIT",
  "NTEXT",
  "NTILE",
  "NULL",
  "NULLIF",
  "NUMERIC",
  "NUMERIC_ROUNDABORT",
  "NVARCHAR",
  "OBJECTPROPERTY",
  "OBJECTPROPERTYEX",
  "OBJECT_DEFINITION",
  "OBJECT_ID",
  "OBJECT_NAME",
  "OBJECT_SCHEMA_NAME",
  "OCTET_LENGTH",
  "OF",
  "OFF",
  "OFFSET",
  "ON",
  "ONLY",
  "OPEN",
  "OPENDATASOURCE",
  "OPENJSON",
  "OPENQUERY",
  "OPENROWSET",
  "OPENXML",
  "OPTIMISTIC",
  "OPTIMIZE",
  "OPTION",
  "OR",
  "ORDER",
  "ORIGINAL_DB_NAME",
  "ORIGINAL_LOGIN",
  "OUT",
  "OUTER",
  "OUTPUT",
  "OVER",
  "OVERRIDE",
  "OWNER",
  "PAGE_VERIFY",
  "PAGLOCK",
  "PARSE",
  "PARSENAME",
  "PARSEONLY",
  "PARTITION",
  "PASSWORD",
  "PATH",
  "PATINDEX",
  "PERCENT",
  "PERCENTILE_CONT",
  "PERCENTILE_DISC",
  "PERCENT_RANK",
  "PERIOD",
  "PERMISSIONS",
  "PERSISTED",
  "PI",
  "PIVOT",
  "PLAN",
  "POWER",
  "PRECEDING",
  "PRECISION",
  "PRIMARY",
  "PRINT",
  "PRIOR",
  "PRIVATE",
  "PROC",
  "PROCEDURE",
  "PWDCOMPARE",
  "PWDENCRYPT",
  "Q",
  "QUERY",
  "QUOTED_IDENTIFIER",
  "QUOTENAME",
  "RADIANS",
  "RAISERROR",
  "RAND",
  "RANGE",
  "RANK",
  "RAW",
  "READ",
  "READCOMMITTED",
  "READCOMMITTEDLOCK",
  "READONLY",
  "READTEXT",
  "READUNCOMMITTED",
  "READ_ONLY",
  "REAL",
  "REBUILD",
  "RECEIVE",
  "RECOMPILE",
  "RECONFIGURE",
  "RECOVERY",
  "REFERENCES",
  "RELATIVE",
  "REMOTE",
  "REMOTE_PROC_TRANSACTIONS",
  "REORGANIZE",
  "REPEATABLE",
  "REPEATABLEREAD",
  "REPLACE",
  "REPLICATE",
  "REPLICATION",
  "RESTORE",
  "RESULT",
  "RETURN",
  "RETURNS",
  "REVERSE",
  "REVERT",
  "REVOKE",
  "RIGHT",
  "RIGHT_SHIFT",
  "ROLE",
  "ROLLBACK",
  "ROLLUP",
  "ROOT",
  "ROUND",
  "ROW",
  "ROWCOUNT",
  "ROWCOUNT_BIG",
  "ROWLOCK",
  "ROWS",
  "ROWVERSION",
  "ROW_NUMBER",
  "RTRIM",
  "RULE",
  "S",
  "SAVE",
  "SCHEMA",
  "SCHEMABINDING",
  "SCHEMA_ID",
  "SCHEMA_NAME",
  "SCHEME",
  "SCOPE_IDENTITY",
  "SCROLL",
  "SCROLL_LOCKS",
  "SELECT",
  "SELF",
  "SEMANTICKEYPHRASETABLE",
  "SEMANTICSIMILARITYDETAILSTABLE",
  "SEMANTICSIMILARITYTABLE",
  "SEND",
  "SEQUENCE",
  "SERIALIZABLE",
  "SERVER",
  "SERVERPROPERTY",
  "SERVICE",
  "SESSIONPROPERTY",
  "SESSION_CONTEXT",
  "SESSION_USER",
  "SET",
  "SETERROR",
  "SETS",
  "SETUSER",
  "SET_BIT",
  "SHOWPLAN_ALL",
  "SHOWPLAN_TEXT",
  "SHOWPLAN_XML",
  "SHUTDOWN",
  "SIGN",
  "SIGNBYASYMKEY",
  "SIGNBYCERT",
  "SIN",
  "SIZE",
  "SMALLDATETIME",
  "SMALLDATETIMEFROMPARTS",
  "SMALLINT",
  "SMALLMONEY",
  "SNAPSHOT",
  "SOME",
  "SOUNDEX",
  "SOURCE",
  "SPACE",
  "SQL_VARIANT",
  "SQL_VARIANT_PROPERTY",
  "SQRT",
  "SQUARE",
  "START",
  "STATIC",
  "STATISTICS",
  "STATISTICS_IO",
  "STATISTICS_PROFILE",
  "STATISTICS_TIME",
  "STATISTICS_XML",
  "STATS",
  "STATS_DATE",
  "STDEV",
  "STDEVP",
  "STR",
  "STRING_AGG",
  "STRING_ESCAPE",
  "STUFF",
  "SUBSCRIPTION",
  "SUBSTRING",
  "SUM",
  "SUSER_ID",
  "SUSER_NAME",
  "SUSER_SID",
  "SUSER_SNAME",
  "SWITCH",
  "SWITCHOFFSET",
  "SYMKEYPROPERTY",
  "SYMMETRIC",
  "SYNONYM",
  "SYSDATETIME",
  "SYSDATETIMEOFFSET",
  "SYSNAME",
  "SYSTEM",
  "SYSTEM_TIME",
  "SYSTEM_USER",
  "SYSTEM_VERSIONING",
  "SYSUTCDATETIME",
  "TABLE",
  "TABLESAMPLE",
  "TABLOCK",
  "TABLOCKX",
  "TAN",
  "TAPE",
  "TARGET",
  "TERTIARY_WEIGHTS",
  "TEXT",
  "TEXTPTR",
  "TEXTSIZE",
  "TEXTVALID",
  "THEN",
  "THROW",
  "TIES",
  "TIME",
  "TIMEFROMPARTS",
  "TIMESTAMP",
  "TINYINT",
  "TO",
  "TODATETIMEOFFSET",
  "TOP",
  "TOSTRING",
  "TRAN",
  "TRANSACTION",
  "TRANSLATE",
  "TRIGGER",
  "TRIM",
  "TRUNCATE",
  "TRY",
  "TRY_CAST",
  "TRY_CONVERT",
  "TRY_PARSE",
  "TYPE",
  "TYPEPROPERTY",
  "TYPE_ID",
  "TYPE_NAME",
  "TZOFFSET",
  "UNBOUNDED",
  "UNCOMMITTED",
  "UNDEFINED",
  "UNICODE",
  "UNION",
  "UNIQUE",
  "UNIQUEIDENTIFIER",
  "UNKNOWN",
  "UNLIMITED",
  "UNPIVOT",
  "UPDATE",
  "UPDATETEXT",
  "UPDLOCK",
  "UPPER",
  "URL",
  "USE",
  "USER",
  "USER_ID",
  "USER_NAME",
  "USING",
  "VALUE",
  "VALUES",
  "VAR",
  "VARBINARY",
  "VARCHAR",
  "VARP",
  "VARYING",
  "VERIFYSIGNEDBYASYMKEY",
  "VERIFYSIGNEDBYCERT",
  "VERSION",
  "VIEW",
  "VIEW_METADATA",
  "WAITFOR",
  "WHEN",
  "WHERE",
  "WHILE",
  "WINDOWS",
  "WITH",
  "WITHIN",
  "WITHOUT",
  "WITHOUT_ARRAY_WRAPPER",
  "WORK",
  "WRITETEXT",
  "XACT_ABORT",
  "XACT_STATE",
  "XLOCK",
  "XML",
  "XMLDATA",
  "XMLSCHEMA",
  "XSINIL",
  "ZONE",
};

static const int KEYWORD_COUNT = sizeof(KEYWORDS) / sizeof(KEYWORDS[0]);

/* Case-insensitive strcmp: returns <0, 0, >0 like strcmp */
static int ci_strcmp(const char *a, const char *b) {
  while (*a && *b) {
    char ca = (*a >= 'a' && *a <= 'z') ? *a - 32 : *a;
    char cb = (*b >= 'a' && *b <= 'z') ? *b - 32 : *b;
    if (ca != cb) return ca - cb;
    a++;
    b++;
  }
  /* Handle different lengths */
  unsigned char ua = (*a >= 'a' && *a <= 'z') ? *a - 32 : *a;
  unsigned char ub = (*b >= 'a' && *b <= 'z') ? *b - 32 : *b;
  return ua - ub;
}

/* Binary search on sorted KEYWORDS array */
static int is_keyword(const char *word) {
  int lo = 0, hi = KEYWORD_COUNT - 1;
  while (lo <= hi) {
    int mid = lo + (hi - lo) / 2;
    int cmp = ci_strcmp(word, KEYWORDS[mid]);
    if (cmp == 0) return 1;
    if (cmp < 0) hi = mid - 1;
    else lo = mid + 1;
  }
  return 0;
}

static int is_id_start(int32_t c) {
  return (c >= 'A' && c <= 'Z') ||
         (c >= 'a' && c <= 'z') ||
         c == '_' || c == '#';
}

static int is_id_continue(int32_t c) {
  return is_id_start(c) ||
         (c >= '0' && c <= '9') ||
         c == '$' || c == '@';
}

/* --- Required tree-sitter external scanner API --- */

/* ASCII-order strcmp for keyword sort verification (uppercase compare) */
static int ascii_strcmp(const char *a, const char *b) {
  while (*a && *b) {
    if ((unsigned char)*a != (unsigned char)*b)
      return (unsigned char)*a - (unsigned char)*b;
    a++;
    b++;
  }
  return (unsigned char)*a - (unsigned char)*b;
}

void *tree_sitter_TSQL_external_scanner_create(void) {
  /* Verify KEYWORDS array is sorted on first use */
  for (int i = 1; i < KEYWORD_COUNT; i++) {
    if (ascii_strcmp(KEYWORDS[i - 1], KEYWORDS[i]) >= 0) {
      fprintf(stderr,
        "tree-sitter-tsql: KEYWORDS sort error at index %d: \"%s\" >= \"%s\"\n",
        i, KEYWORDS[i - 1], KEYWORDS[i]);
      abort();
    }
  }
  return NULL;  /* stateless scanner */
}

void tree_sitter_TSQL_external_scanner_destroy(void *payload) {
  /* nothing to free */
}

unsigned tree_sitter_TSQL_external_scanner_serialize(void *payload, char *buffer) {
  return 0;  /* no state to serialize */
}

void tree_sitter_TSQL_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  /* no state to restore */
}

bool tree_sitter_TSQL_external_scanner_scan(
    void *payload, TSLexer *lexer, const bool *valid_symbols) {

  if (!valid_symbols[NON_KEYWORD_ID]) {
    return false;
  }

  /* Skip whitespace */
  while (lexer->lookahead == ' ' || lexer->lookahead == '\t' ||
         lexer->lookahead == '\r' || lexer->lookahead == '\n') {
    lexer->advance(lexer, true);
  }

  /* Check if current char can start an identifier */
  if (!is_id_start(lexer->lookahead)) {
    return false;
  }

  /* Let TEMP_ID_ handle #-prefixed identifiers (temp tables/procs) */
  if (lexer->lookahead == '#') {
    return false;
  }

  /* Read the full identifier into a buffer */
  char buffer[256];
  int length = 0;

  while (is_id_continue(lexer->lookahead) && length < 255) {
    buffer[length++] = (char)lexer->lookahead;
    lexer->advance(lexer, false);
  }
  buffer[length] = '\0';

  /* Reject if it's ANY grammar keyword */
  if (is_keyword(buffer)) {
    return false;
  }

  lexer->result_symbol = NON_KEYWORD_ID;
  return true;
}
